"""
config.py
================================================================================
WHAT THIS FILE IS
--------------------------------------------------------------------------------
One small record -- the Project -- holding everything that differs between one
project and the next. Everything else in this folder is shared code that reads
this record; nothing else in rdm_diagrams/ knows the word "fluke" or the word
"groundfish".

If you are adding a THIRD project, you do not edit this file. You write a new
projects/<name>.py holding a Project(...) with the five required fields, and a
make_<name>_diagrams.py next to it. See README.md.

--------------------------------------------------------------------------------
WHY THE DEFAULTS ARE HERE
--------------------------------------------------------------------------------
Several settings that look project-specific turned out to be identical in both
existing projects: which folders to skip, which extensions count as data, and
where the master Stata wrapper lives. They are defaults on this record rather
than lines repeated in every project file, so a project only has to state what
is genuinely its own. A project that IS different just passes its own value.
================================================================================
"""

import os
from dataclasses import dataclass, field


# The folder this whole toolchain lives in (the "diagrams" folder). Used to
# place the output folders, so the diagrams land in the same place no matter
# which folder you happen to be sitting in when you run the script.
TOOLCHAIN_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# The drawing programs a diagram can be rendered with. Both produce the same
# filenames in the same folder; only the layout differs.
#
# Mermaid is the default: it draws the comprehensive diagram with about a third
# fewer line crossings (measured -- tests/check_layout.py, and
# diagram_spikes/results/RESULTS.md for how that was decided). Graphviz is
# still here and still works, selected with --engine=graphviz; it is the
# fallback on a machine without Node, and it is the one to use for the
# simplified diagram when it has to fit a slide, since Mermaid cannot scale a
# finished drawing to a page. See MERMAID_MIGRATION_PLAN.md, Phase 6, for what
# would have to be true before the Graphviz path is removed altogether.
#
# It lives HERE rather than in __init__.py because the three renderer modules
# need it too, for the default on their own render() -- and they are imported
# BY __init__.py, so importing it from there would be a circular import. One
# definition, no copies to drift.
ENGINES = ("graphviz", "mermaid")
DEFAULT_ENGINE = "mermaid"


@dataclass(frozen=True)
class Project:
    """One project's worth of settings: paths, names, and the curation list.

    Required:
      key            short lower-case name; also the output subfolder name
      display_name   how the project is written in titles and captions
      output_prefix  goes on the front of every picture filename
      repo           absolute path to the source repository being read
      curation       the hand-maintained curation dictionary (see extract.py)
    """

    key: str
    display_name: str
    output_prefix: str
    repo: str
    curation: dict = field(repr=False)

    # --- Settings that are currently the same for every project --------------
    # Stated here once. A project that differs passes its own value.

    # Where the master Stata wrapper sits inside the repository. Its structure
    # is what gives us execution order and the on/off toggles.
    wrapper_relpath: str = "Code/pre_sim/model_wrapper.do"

    # Folders we deliberately do not walk into. test_code and archive hold
    # experiments and retired scripts -- real files, but not part of the
    # pipeline, and including them would bury the picture in noise.
    skip_folders: frozenset = frozenset(
        {".git", ".devcontainer", "test_code", "archive", "renv", "output"})

    # The file extensions we treat as "this is a data file, not a script".
    data_extensions: tuple = ("dta", "csv", "xlsx", "fst", "Rds", "rds",
                              "feather", "png")

    # An importable module holding a hand-typed list of boxes and arrows, for
    # --check to compare the extraction against. None means this project has no
    # such historical snapshot, and --check has nothing to compare with. Do NOT
    # point this at a file that reads pipeline_data_generated.py: that would be
    # comparing the extraction with itself, and the check could never fail.
    reference_module: "str | None" = None

    # The folder that snapshot file lives in. The snapshots were deliberately
    # left where they were written -- they are session records of an abandoned
    # approach, not part of this toolchain -- so the folder has to be stated
    # rather than assumed. Empty means "the diagrams folder".
    reference_dir: str = ""

    @property
    def repo_name(self):
        """The repository's folder name, e.g. 'flukeRDM'.

        Used where the prose refers to the folder on disk rather than to the
        project as a whole ("walks flukeRDM/, reading only .do and .R files").
        """
        return os.path.basename(self.repo.rstrip("/\\"))

    @property
    def wrapper(self):
        """Full path to the master Stata wrapper."""
        return os.path.join(self.repo, *self.wrapper_relpath.split("/"))

    @property
    def output_dir(self):
        """Full path to this project's output folder, created if missing."""
        path = os.path.join(TOOLCHAIN_DIR, "output", self.key)
        os.makedirs(path, exist_ok=True)
        return path

    @property
    def archive_dir(self):
        """Full path to this project's archive of previous versions.

        Unlike output_dir this does NOT create the folder, because the archive
        is read on every run and only written on the runs that change a
        picture -- creating it here would leave an empty archive/ sitting in the
        output folder of a project that has never had anything to archive. The
        folder is made at the moment something is written to it.

        Nothing is ever deleted from the archive -- see README.md.
        """
        return os.path.join(self.output_dir, "archive")

    @property
    def data_module(self):
        """Full path to the pipeline description the extractor writes."""
        return os.path.join(self.output_dir, "pipeline_data_generated.py")

    @property
    def compare_page(self):
        """Full path to the previous-versus-current comparison page."""
        return os.path.join(self.output_dir, "compare.html")

    def output_base(self, name):
        """Full path (no extension) for one picture, e.g. '..._simple_pipeline_diagram'."""
        return os.path.join(self.output_dir, self.output_prefix + name)

    def output_name(self, name, ext):
        """Just the filename of one picture, e.g. 'FlukeRDM_simple_...diagram.png'."""
        return self.output_prefix + name + "." + ext

    def problem(self):
        """Return a plain-language description of the first thing that is wrong.

        Returns None when everything checks out. This exists because a wrong
        repo path is the failure that actually happened: a path fix landed in
        one copy of the toolchain and not the other, and the extractor read an
        empty folder for weeks without complaining. Checking here means all
        the entry points get the same clear message instead of a traceback.
        """
        if not os.path.isdir(self.repo):
            return ("Could not find the %s source code at:\n"
                    "    %s\n"
                    "Fix the 'repo' path in projects/%s.py."
                    % (self.display_name, self.repo, self.key))
        if not os.path.isfile(self.wrapper):
            return ("Found the %s folder, but not the master wrapper inside it:\n"
                    "    %s\n"
                    "Fix 'wrapper_relpath' in projects/%s.py if the wrapper moved."
                    % (self.display_name, self.wrapper, self.key))
        return None
